import api from './axios'

export const createWorkspace   = (data)             => api.post('/workspaces/', data)
export const listWorkspaces    = ()                  => api.get('/workspaces/')
export const getWorkspace      = (slug)              => api.get(`/workspaces/${slug}`)
export const inviteMember      = (workspaceId, data) => api.post(`/workspaces/${workspaceId}/members`, data)
export const listMembers       = (workspaceId)       => api.get(`/workspaces/${workspaceId}/members`)
export const listChannels      = (workspaceId)       => api.get(`/channels/${workspaceId}/channels`)
export const createChannel     = (workspaceId, data) => api.post(`/channels/${workspaceId}/channels`, data)
export const addChannelMember    = (channelId, data)         => api.post(`/channels/channel/${channelId}/members`, data)
export const getChannelMembers   = (channelId)               => api.get(`/channels/channel/${channelId}/members`)
export const removeChannelMember = (channelId, userId)       => api.delete(`/channels/channel/${channelId}/members/${userId}`)
export const getInvitations    = ()                  => api.get('/workspaces/invitations')
export const acceptInvitation  = (id)                => api.post(`/workspaces/invitations/${id}/accept`)
export const declineInvitation = (id)                => api.post(`/workspaces/invitations/${id}/decline`)
export const leaveWorkspace    = (workspaceId)       => api.delete(`/workspaces/${workspaceId}/leave`)
export const deleteWorkspace   = (workspaceId)       => api.delete(`/workspaces/${workspaceId}`)
